In [2]:
test="Hello World"
print(test)

Hello World


In [ ]:
import numpy as np

one_dimentional_arr = np.array([10,12])
print(one_dimentional_arr)

a = np.array([1,2,3])
print(a)

b = np.arange(3)
print(b)

c = np.arange(1,20,3)
print(c)

lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)



[10 12]
[1 2 3]
[0 1 2]
[ 1  4  7 10 13 16 19]
[  0.  25.  50.  75. 100.]
